---
- name: ansible-vmware-install-ccm
  hosts: cc-manager
  
  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailabl
  handlers:
    - name: Restart server
      command: shutdown -r 1 "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-monitor
          port=22
          delay=1
          timeout=120

  tasks:
   - name: Install Wget
     raw: yum -y install wget
   - name: Step 0a - download cc-host-install-start.sh
     raw: wget http://straube.ch/cisco/00_cc-host-install-start.sh -P $HOME
   - name: Step 0b - chmod +x 00_cc-host-install-start.sh
     command: chmod +x 00_cc-host-install-start.sh
   - name: Step 0c - exec 00_cc-host-install-start.sh
     command: sh $HOME/00_cc-host-install-start.sh
   - name: Step 1 - Update hosts file with hosts file from ansible server
     copy: src=/etc/hosts dest=/etc/hosts
   - name: Step 3 - chmod +x installer for VMware CloudCenter Manager
     raw: chmod +x /tmp/cc-binary/core_installer.bin
   - name: Step 4 - Execute installer for VMware CloudCenter Manager
     command: sh /tmp/cc-binary/core_installer.bin centos7 vmware ccm
   - name: Step 5 - Execute Java installer
     command: java -jar /tmp/cc-binary/ccm-installer.jar /tmp/cc-binary/ccm-response.xml
   - name: Step 8a - execute mail.properties.py
     raw: python /tmp/cc-install-automation/cc-property-scripts/00-ccm-mail.properties.py '10.15.0.51' '' ''
   - name: Step 8b - execute server.properties.py
     raw: python /tmp/cc-install-automation/cc-property-scripts/00_ccm-server.properties.py 'cc-manager' 'cc-manager' 'https://cc-monitor:8443'
   - name: Step 8c - execute mgmt.properties.py
     raw: python /tmp/cc-install-automation/cc-property-scripts/00_ccm-mgmt.properties.py
   - name: restart in 60 sec
     raw: shutdown -r 1