---
- name: ansible-vmware-install-ccm
  hosts: cc-manager-01
  vars:
    user: "{{ USER }}"
    password: "{{ PASSWORD }}"
    cc_binary_url: "{{ CC_BINARY_URL }}"

  
  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailabl
  handlers:
    - name: Restart server
      command: shutdown -r 1 "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-manager-01
          port=22
          delay=1
          timeout=120

  tasks:
  - name: Step 1 git clone
    raw: git clone https://github.com/HybridCloudAutomation/cloudcenter-automated-installation.git /tmp/cloudcenter-automated-installation
  - name: Step 2 - exec 00_prepare-host.sh
    command: sh /tmp/cloudcenter-automated-installation/00_prepare-host.sh "{{ user }}" "{{ password }}" "{{ cc_binary_url }}"
  - name: Step 3 - Update hosts file with hosts file from ansible server
    copy: src=/etc/hosts dest=/etc/hosts
  - name: Step 4 - chmod +x installer for VMware CloudCenter Manager
    raw: chmod +x /tmp/cc-binary/core_installer.bin
  - name: Step 5 - Execute installer for VMware CloudCenter Manager
    command: sh /tmp/cc-binary/core_installer.bin centos7 vmware ccm
  - name: Step 6 - Execute Java installer
    command: java -jar /tmp/cc-binary/ccm-installer.jar /tmp/cc-binary/ccm-response.xml
  - name: Step 7 - execute mail.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/00-ccm-mail.properties.py '10.15.0.51' '' ''
  - name: Step 8 - execute server.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/00_ccm-server.properties.py 'cc-manager-01' 'cc-manager-01' 'https://cc-monitor-01:8443'
  - name: Step 9 - execute mgmt.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/00_ccm-mgmt.properties.py
  - name: restart in 60 sec
    raw: shutdown -r 1