---
- name: ansible-vmware-install-cchm
  # Use host or group defined in /etc/ansible/hosts
  hosts: cc-monitor

  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailabl
  handlers:
    - name: Restart server
      command: shutdown -r 1 "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-monitor
          port=22
          delay=1
          timeout=120

  tasks:
  - name: Install Wget
    raw: yum -y install wget
  - name: Step 0a - download cc-host-install-start.sh
    raw: wget http://straube.ch/cisco/00_cc-host-install-start.sh -P $HOME
  - name: Step 0b - chmod +x 00_cc-host-install-start.sh
    command: chmod +x $HOME/00_cc-host-install-start.sh
  - name: Step 0c - exec 00_cc-host-install-start.sh
    command: sh $HOME/00_cc-host-install-start.sh
  - name: Step 1 - Update hosts file with hosts file from ansible server
    copy: src=/etc/hosts dest=/etc/hosts
  - name: Step 3 - chmod +x installer for VMware CloudCenter Manager
    raw: chmod +x /tmp/cc-binary/core_installer.bin
  - name: Step 4 - Execute installer for VMware CloudCenter Monitor
    command: sh /tmp/cc-binary/core_installer.bin centos7 vmware monitor
  - name: Step 5 - Execute Java installer
    command: java -jar /tmp/cc-binary/monitor-installer.jar /tmp/cc-binary/monitor-response.xml
  - name: Step 8c - 01_ccmon-monitor.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/01_ccmon-monitor.properties.py '1' 'cc-manager'
  - name: restart in 60 sec
    raw: shutdown -r 1
