---
- name: ansible-vmware-install-cco
  # Use host or group defined in /etc/ansible/hosts
  hosts: cc-orchestrator-01

  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailable
  handlers:
    - name: Restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-orchestrator-01
          port=22
          delay=1
          timeout=60
 
  tasks:
  - name: Install Wget
    raw: yum -y install wget
  - name: Step 0a - download 00_cc-host-install-start.sh
    raw: wget http://straube.ch/cisco/00_cc-host-install-start.sh -P $HOME
  - name: Step 0b - exec 00_cc-host-install-start.sh
    command: sh $HOME/00_cc-host-install-start.sh
  - name: Step 1 - Update hosts file with hosts file from ansible server
    copy: src=/etc/hosts dest=/etc/hosts
  - name: Step 3 - chmod +x installer for VMware CloudCenter Manager
    raw: chmod +x /tmp/cc-binary/core_installer.bin
  - name: Step 4 - Execute installer for VMware CloudCenter Orchestrator
    command: sh /tmp/cc-binary/core_installer.bin centos7 vmware cco
  - name: Step 5 - Execute Java installer
    command: java -jar /tmp/cc-binary/cco-installer.jar /tmp/cc-binary/cco-response.xml
  - name: Step 8a - execute mail.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/03_cco-gateway.properties.py '1' 'cc-manager'
  - name: Step 8a - execute mail.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/03_cco-rev_connection.properties.py 'cc-amqp-01' '7788' '7789'
  - name: Step 8a - execute mail.properties.py
    raw: python /tmp/cc-install-automation/cc-property-scripts/03_cco-rabbit-gateway.properties.py 'cc-amqp-01' '5671'
  - name: restart in 60 sec
    raw: shutdown -r 1