---
- name: ansible-vmware-install-cca
  # Use host or group defined in /etc/ansible/hosts
  hosts: cc-amqp-01
  gather_facts: no
  vars:
    user: "{{ USER }}"
    password: "{{ PASSWORD }}"
    cc_binary_url: "{{ CC_BINARY_URL }}"

  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailable
  handlers:
    - name: Restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-amqp-01
          port=22
          delay=1
          timeout=60
  tasks:
  - name: Step 1 git clone
    raw: git clone https://github.com/HybridCloudAutomation/cloudcenter-automated-installation.git /tmp/cloudcenter-automated-installation
  - name: Step 2 - exec 00_prepare-host.sh
    command: sh /tmp/cloudcenter-automated-installation/00_prepare-host.sh "{{ user }}" "{{ password }}" "{{ cc_binary_url }}"
  - name: Step 3 - Update hosts file with hosts file from ansible server
    copy: src=/etc/hosts dest=/etc/hosts
  - name: Step 4 - Execute installer for VMware RabbitMQ
    command: sh /tmp/cc-binary/core_installer.bin centos7 vmware rabbit
  - name: Step 5 - Clear the IP tables rules to enable access to non-standard ports (5671)
    command: iptables -F
  - name: Step 6 - Execute Java installer
    command: java -jar /tmp/cc-binary/cco-installer.jar /tmp/cc-binary/conn_broker-response.xml
  - name: Step 7 - execute 02_cca-gateway_config.properties.py 'cc-manager'
    raw: python /tmp/cloudcenter-automated-installation/cc-install-automation/cc-property-scripts/02_cca-gateway_config.properties.py 'cc-manager'
  - name: Step 8 - 02_cca-gua.properties.py 'cc-orchestrator-01'
    raw: python /tmp/cloudcenter-automated-installation/cc-install-automation/cc-property-scripts/02_cca-gua.properties.py 'cc-orchestrator-01'
  - name: restart in 60 sec
    raw: shutdown -r 1