---
- name: ansible-vmware-install-cco
  # Use host or group defined in /etc/ansible/hosts
  hosts: cc-orchestrator-01
  vars:
    user: "{{ USER }}"
    password: "{{ PASSWORD }}"
    cc_binary_url: "{{ CC_BINARY_URL }}"
    
  # raw: wget http://straube.ch/cisco/cc-automated-installation/00_start-install.sh -P $HOME
  # This handler is rebooting the target host and waiting for it to come back online
  # Once the shutdown is initiated, the status cannot be verified which leads to the task state unavailable
  handlers:
    - name: Restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=cc-orchestrator-01
          port=22
          delay=1
          timeout=60
 
  tasks:
  - name: Step 1 git clone
    raw: git clone https://github.com/HybridCloudAutomation/cloudcenter-automated-installation.git /tmp
  - name: Step 2 - exec 00_prepare-host.sh
    command: sh /tmp/cloudcenter-automated-installation/00_prepare-host.sh "{{ user }}" "{{ password }}" "{{ cc_binary_url }}"
  - name: Step 3 - Update hosts file with hosts file from ansible server
    copy: src=/etc/hosts dest=/etc/hosts
  - name: Step 4 - Execute installer for VMware CloudCenter Orchestrator
    command: sh /tmp/cc-binary/core_installer.bin centos7 vmware cco
  - name: Step 5 - Execute Java installer
    command: java -jar /tmp/cc-binary/cco-installer.jar /tmp/cc-binary/cco-response.xml
  - name: Step 6 - execute 03_cco-gateway.properties.py '1' 'cc-manager'
    raw: python /tmp/cloudcenter-automated-installation/cc-install-automation/cc-property-scripts/03_cco-gateway.properties.py '1' 'cc-manager'
  - name: Step 7 - execute 03_cco-rev_connection.properties.py 'cc-amqp-01' '7788' '7789'
    raw: python /tmp/cloudcenter-automated-installation/cc-install-automation/cc-property-scripts/03_cco-rev_connection.properties.py 'cc-amqp-01' '7788' '7789'
  - name: Step 8 - execute mail.properties.py
    raw: python /tmp/cloudcenter-automated-installation/cc-install-automation/cc-property-scripts/03_cco-rabbit-gateway.properties.py 'cc-amqp-01' '5671'
  - name: restart in 60 sec
    raw: shutdown -r 1